### ISSUE TITLE
Incompatibilidad: peer dependency de react@19.0.0 con @react-native-community/datetimepicker (Expo SDK 53)

### ISSUE THREAD

**Issue by ROBER-SALAMA** [mmazzarolo/react-native-modal-datetime-picker#778]
## Versions

* **`expo`**: `~53.0.0`
* **`react`**: `19.0.0`
* **`react-native`**: `0.79.3`
* **`react-native-modal-datetime-picker`**: `18.0.0`
* **`@react-native-community/datetimepicker`**: `^8.4.1`

## Description

I am trying to upgrade my application from **Expo SDK 52 to SDK 53**. Expo SDK 53 introduces **React 19.0.0** and **React Native 0.79.3**.

During the upgrade process, specifically when running `npm install` (or `npx expo install --fix`), I am encountering an `ERESOLVE` error related to a `peer dependency` conflict with `@react-native-community/datetimepicker` and **React 19**.

I have followed the recommended steps, including:
1. update `expo-cli` and `eas-cli`.
2.  Run `npx expo install expo@^53.0.0.0`.
3.  Clean `node_modules` and `package-lock.json`.

**I confirmed that `react-native-modal-datetime-picker` is at its latest version `18.0.0.0`.

Following the template directions, **I uninstalled `react-native-modal-datetime-picker` and tried to directly use `@react-native-community/datetimepicker` (version `8.4.1`)**. Unfortunately, the `ERESOLVE` problem with the `peer dependency` of `react@19.0.0` **persists even when using the community component directly**. This suggests that the current version of `@react-native-community/datetimepicker` may not be fully compatible with React 19.

The exact error I receive is as follows.

Translated with [DeepL.com](https://www.deepl.com/?utm_campaign=product&utm_source=web_translator&utm_medium=web&utm_content=copy_free_translation) (free version)

npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: e-billing@1.0.1
npm ERR! Found: @react-native-community/datetimepicker@8.2.0
npm ERR! node_modules/@react-native-community/datetimepicker
npm ERR!   @react-native-community/datetimepicker@"8.3.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! @react-native-community/datetimepicker@"8.3.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react@19.0.0
npm ERR! node_modules/react
npm ERR!   peer react@"^19.0.0" from react-native@0.79.3
npm ERR!   node_modules/react-native
npm ERR!     react-native@"0.79.3" from the root project
npm ERR!     peer react-native@"*" from @react-native-community/datetimepicker@8.3.0

I was hoping that the dependency installation would complete without errors, allowing the successful upgrade to Expo SDK 53.

I would appreciate any guidance on whether there is an update planned to address this incompatibility with React 19, or any workarounds. thanks!

**Comment by Engazan** [comment]
@ROBER-SALAMA have u found any alternative package for this ? cuz google requriring Android 15 support witch is SDK 53 and this package seems dead to me

**Comment by tsfento** [comment]
> [@ROBER-SALAMA](https://github.com/ROBER-SALAMA) have u found any alternative package for this ? cuz google requriring Android 15 support witch is SDK 53 and this package seems dead to me

Just FYI, you don't need to have SDK 53 to support Android 15. You can set the supported version manually in your app.json or app.config: [https://docs.expo.dev/versions/latest/sdk/build-properties/#example-appjson-with-config-plugin](https://docs.expo.dev/versions/latest/sdk/build-properties/#example-appjson-with-config-plugin) (Android SDK 35 would be for Android 15 support).

**Comment by vshkl** [comment]
I'd suggest overriding lock file whenever performing major updates like Expo 52 → 52 migration.

With these versions:
```JSON
"@react-native-community/datetimepicker": "8.4.1",
"expo": "53.0.19",
"react": "19.0.0",
"react-native": "0.79.5",
"react-native-modal-datetime-picker": "^18.0.0",
```
nothing seems to enforce React 18 here:
```YAML
"react-native-modal-datetime-picker@npm:^18.0.0":
  version: 18.0.0
  resolution: "react-native-modal-datetime-picker@npm:18.0.0"
  dependencies:
    prop-types: "npm:^15.7.2"
  peerDependencies:
    "@react-native-community/datetimepicker": ">=6.7.0"
    react-native: ">=0.65.0"
```
and
```YAML
"@react-native-community/datetimepicker@npm:8.4.1":
  version: 8.4.1
  resolution: "@react-native-community/datetimepicker@npm:8.4.1"
  dependencies:
    invariant: "npm:^2.2.4"
  peerDependencies:
    expo: ">=52.0.0"
    react: "*"
    react-native: "*"
    react-native-windows: "*"
  peerDependenciesMeta:
    expo:
      optional: true
    react-native-windows:
      optional: true
```
